### ISSUE TITLE
`SyntaxError: Unexpected token '?'` in v1.0.51-alpha.2

### ISSUE THREAD

**Issue by jim80net** [scribd/amazon-servicediscovery-service-action#168]
[v1.0.51-alpha.2](https://github.com/scribd/amazon-servicediscovery-service-action/releases/tag/v1.0.51-alpha.2) build results in `SyntaxError: Unexpected token '?'`

```
/home/runner/work/_actions/scribd/amazon-servicediscovery-service-action/alpha/dist/index.js:4055
        useDualstackEndpoint: options.useDualstackEndpoint ?? false,
                                                            ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:[27](https://github.com/SlideShareCorp/slideshare-web-app/actions/runs/3605330446/jobs/6075952610#step:7:28))
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:[32](https://github.com/SlideShareCorp/slideshare-web-app/actions/runs/3605330446/jobs/6075952610#step:7:33))
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by jim80net** [comment]
https://github.com/SlideShareCorp/slideshare-web-app/actions/runs/3605330420/jobs/6075612276

**Comment by jim80net** [comment]
This was fixed by https://github.com/scribd/amazon-servicediscovery-service-action/commit/4291e0c91d3efb88f186a5867a0800546e183959
